### ISSUE TITLE
Ability to add or change attacks for deathknight, 

### ISSUE THREAD

**Issue by stunshock** [wowsims/wotlk#1007]
**Is your feature request related to a problem? Please describe.**

I want to sim an unholy 2h build with obliterate taking anihilation instead of endless winter and scourge strike.

**Describe the solution you'd like**

Be able to swap out death strike, scourge strike, and obliteration for every spec

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by rosenrusinov** [comment]
We don't plan to support weird specs that are sub-optimal due to the amount of such possible specs on DK. If a spec that actually works is found we will be adding it as supported.

> I want to sim an unholy 2h build with obliterate taking anihilation instead of endless winter and scourge strike.
I added this as someone else also requested it and it is a dps loss as predicted. Picking up Annihilation and not SS and having an unholy spec with gargoyle should activate this rotation
