### ISSUE TITLE
User Accounts

### ISSUE THREAD

**Issue by bomberjester** [wowsims/wotlk#1221]
I'd really like the ability to have an account so that I can save a character (or characters) and easily switch between them.  having everything work based on cookies or session data makes it problematic to share with friends (since doing so blew up their session data when they clicked my link)
for example, the way 80 upgrades manages characters is amazing.  combine that with your awesome sim setup and it would be a match made in heaven!

**Comment by jimmyt857** [comment]
Had left this open for awhile because it was something we've talked about. However, I think we're pretty settled now that this won't happen anytime soon. Unfortunately, user accounts would require that we run servers, instead of the sim running in users' individual browsers. This would be a complete reworking of the current setup and would be a massive effort.
