### ISSUE TITLE
Aspect Weaving for Hunter Sim

### ISSUE THREAD

**Issue by atropon** [wowsims/wotlk#1257]
Would be cool if you added a check box for aspect weaving in addition Viper Start/Stop Mana %.

In order to lose minimal damage when using *Aspect of the Viper*, it is only turned on before casting a *Steady Shot* (the "filler" ability which deals the least damage and is only used when every other ability is on cooldown). When another damaging ability comes off cooldown, the hunter switches back to *Aspect of the Dragonhawk*. (As aspects can be switched during GCD, this can be executed without interupting the rotation at all.)
(Obviously, this can be combined with the *Viper Start/Stop Mana %* feature, simulating the hunter to start aspect weaving only when the mana falls below the specified threshold. However, *Viper Start/Stop Mana %* and *Aspect Weaving Start/Stop Mana %* might should be seperate features as a hunter still could decide to go full viper when their mana falls very low.)

Without this feature, the value of Int/Mp5, is strongly overestimated and the simulated damage falls behind the real damage.

An output telling the user which perentage of the fight they would need to aspect weave to go oom just in the momen when the boss dies would be quite handy as well.

**Comment by jimmyt857** [comment]
After chatting a bit in the hunter discord, it seems like this isn't a very important feature because 1) in most scenarios you shouldn't have enough mana issues to need viper and 2) if you do, fixing your mana issues is much better for dps than trying to min-max viper.

Going to leave this issue open for awhile in case anyone else wants to chime in but will probably not implement this unless the need become more clear.
