### ISSUE TITLE
Hunter sim issues with hit cap and scopes

### ISSUE THREAD

**Issue by tSquand** [wowsims/wotlk#1305]
**Describe the bug**
The sim doesn't seem to calculate the value of hit rating properly,  it values hit as the most effective stat even far above hit cap, not sure if it includes the Focused Aim talent in the calculation.
Also, when selecting the scope for ranged weapon it doesn't show the EP and I'm not sure if they are accounted for in the sim.
**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22]Version 106.0.5249.119 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
The EP doesn't update automatically, you need to run `Calculate` in the `Stat Weights` menu for it to do that.

The scope EP doesn't show because its ranged-only hit which is implemented differently internally, but it is indeed accounted for in the sim. You can confirm this by simming the difference between any scope vs no scope.
