### ISSUE TITLE
Combat Rogue sim favoring fast/fast due to poison proc rates being incorrect

### ISSUE THREAD

**Issue by ch0nx** [wowsims/wotlk#1482]
**Describe the bug**
The combat rogue dps simulation seems to be favoring fast/fast over slow/fast weapons, and from what I can tell this is because it is not calculating the poison procs correctly.  For example, running 2x Hailstorm swords in a sword spec on a 3min fight, the sim thinks there will be 216 instant poison procs.  This is not accurate at all, is it still using the old formula?

**To Reproduce**
1.  Sim a known-bis config of calamity/webbed as combat CQC
2. Sim a sword config of 2x hailstorm
3. Sim a sword config of something slower MH like silent crusader/hailstorm or torment of the banished/hailstorm
4. Observe the DPS loss and poison proc counts

**Expected behavior**
"Normalized" poison proc chances 

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.
Hailstorms:
![image](https://user-images.githubusercontent.com/105817987/198336893-323fdea5-9447-4936-9158-60f3a03f4bbb.png)

Crusader/Hailstorm:
![image](https://user-images.githubusercontent.com/105817987/198336526-5aa11dcb-7ca6-40bb-a1e5-bf5de89912a8.png)

**Comment by b-r-a-n** [comment]
Looks like you have the poisons configured incorrectly in your Slow MH / Fast OH sword run:
For reference:
Calamity/Webbed : 7540 dps [link](https://wowsims.github.io/wotlk/rogue/#eJztUjtIw1AUzb15rWn88BTR6FQziSC8JAR0SnRycBBEEKdOIgjVTXAq4iAFwcXBjk6CdBKC2krxA6XgD0TF1jgIlYIOjh29abq4OejmGQ7v3HPfubyP2qugwAVYxhTAHsAhwC1ADWCcx3EEXJiFZdhoWF1S/xVbg5aZ5GJyaSWpAI/250Dl/CCP2s0L6lHvHK+vUI3x+jPqcuEQ1XbukVl8aUqF3+VQK2dlMipklCpNo4Pfe6hdkGQkJbWV+2Q/ZmUdJMrbPG72cf7+iNrbPg0jGUZu084aRTKePkLiTD7gj5OA/aego0BDLyvBatcLV4yf5lBX6OyRKZZgQ1so/eMbVpkCGs71qG2caTiIQh5BN0J/gHGqp2FQCNsyBbFpDQvTNoVtCFsIyxaGME3LIEcYpm28QptyVkVerKL2dIM1YJ/QkgGpDJLuY6wxLDXvdoZju92+zE6AkjMaVm6dgfkGHhwzi/FpTfnz11p3fyMlVbr4lZyfILyrSd8dC3XdmYAEfAEaI3R+)
Hailstorm/Hailstorm: 7178 dps [link](https://wowsims.github.io/wotlk/rogue/#eJztUr9LQlEUfud41dfrB7eIujnVmyQIru/xwCZfTQ0NQQTR5CRBYG5Bk0RDCEFLQ/4FgTgFYmlEJYhQKURFmg5BIdTQ2NjR51Bbg219w8f57nfud7g/tFEVJa5CDOMAhwBZgApAE2CWj2MQbFiGGOy0rSHFd822wLsUXYuub0RV4B5fDjTOj/Ioyg3UPZlLvLlGrYd/PqHuOsui1s8zZBYbHany2xyKatpFRo2MUq1jDPC7DIoCSUZS0Xp5neyHtEsHhfJ2Tzp9nL89oHhN0TCSTuQ+7WxSJOOJYyRO5lv8ftri+mOrI0VZV7XvFePnOdRVOrt7gYXZ5B4q//iBTaaCwJURrY8zgX6UriDabvoDjKOABPiltExDEhvmlDQsQ1oBUtK0ZMAyDJMEVYYVeIY+9eIFefEFxWMZm8A+wJsEpQqKXsee9rB4xB50xg7bY8mDFkqhaWelEpqItHEfMtI4vijUP3+tbbsbKfFSoSs5v4FzV/N1e8bRn6E5CMMXDYV0eg==)
Crusader/Hailstorm: 7387 dps [link](https://wowsims.github.io/wotlk/rogue/#eJztUj1LA0EQvZlszOX8YBXR1UqvCoKw2eNAq5xWFhaCCGJlFQQh2glWQSwkINhYmF8ghFRCiCYiaiAEjAqiQWMsBCWghWVK53Jp7Cxi5yuGefN232M/jEEdJa7AOsYBDgGyALcAdYBpPoIT4MAirMNOU+rThstsCwILsdXY2kZMB94xnAOD86M8ipsXNDsyl3hdRiPIG89o+s6yaHTzDInFlxbV+V0OxVPaR0KVhFK1JfTw+wyKAlFGVDM6eY3kStpngkZ+uyetdZx/VFC8pyiMqGe5TzvrZMl44hipJvNu/Tx1a+3RXVGh0Kuq26XyXsf4eQ5Nnc7un2PLbGwPtX/8wCbTQeDSgNHFmcAQSt8EOn76A4zTPAEhKW1LSarKGpfKVtIOE5OWLcO2UhYR6pQdfoUu/eINefENxeMN1oF9QSAJ2hNoZg2DzbB41On1YvudoeSBi1Jk0pvcRkajTTxEVBpH5oX+56+17bTDJV4qtMXnN/DuarbmTHm8EZmBZfgGjSx0pQ==)

These results match what you expect because they have the poisons configured correctly.
In the screen shot you provided you might also notice the warning icon in the top right. That warning is probably saying you have the poison on the wrong weapons.
