### ISSUE TITLE
Wasm Load Failure

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#1509]
Creating a master bug for all the different reports of this.

**Comment by jimmyt857** [comment]
Got this image from a user showing the console log when this happens:
![After](https://user-images.githubusercontent.com/1822327/198893812-1d26f6cf-3c7e-4056-8b33-e9a0b0460c11.jpg)

**Comment by Eltsapo** [comment]
Hello. I wanted to ask if you have figured out a way to solve this issue? Is there something I can do to use the simulator? Thanks again

**Comment by Watcher7** [comment]
After working with a user to troubleshoot and resolve this issue I believe a culprit may be in browser ad-blockers (in this case AdBlock).

In order to resolve this issue I had a user issue an exception to the wowsims website, and then issue a cache free reload (control click the refresh button). The cache free reload was required because it seemed the blocking of the asset was cached.

This is a sample size of 1 resolved instance for a users, but it's worth exploring for others.

A quick smoke check is to have the user open the site in an incognito tab, as usually users have add-ons disabled in incognito mode, and it's insulated from caching behavior. If it loads in incognito with add-ons disabled, then it's likely the add-on blocking it.

**Comment by Watcher7** [comment]
I've determined that the issue iOS users are facing is likely due to iOS's memory watchdog (`jetsam`) reaping the tab's worker processes.

I was unable to replicate the issue in the iOS simulator (8/16 GB memory Macbooks), but on a MWKM2LL/A (4GB iPhone 11) test device 
```
   Process com.apple.WebKit.WebContent [18901] killed by jetsam reason highwater
```
events were generated by `osanalyticshelper` which I then determined `com.apple.WebKit.WebContent [18901]` to be a worker process for the `MobileSafari` wowsims tab.

According to https://developer.apple.com/documentation/xcode/identifying-high-memory-use-with-jetsam-event-reports "highwater" is when "A system daemon exceeded its highest-expected memory footprint."

After following the trail to `jetsam`s event log location it seems to have killed the process after it allocated 117383 rpages with a page size of 16384 (~1.9 gigs of memory, documentation states to take rpages * pageSize)

```
 {
    "states" : [
      "frontmost"
    ],
    "idleDelta" : 11,
    "killDelta" : 25223,
    "purgeable" : 0,
    "age" : 270356751,
    "fds" : 25,
    "genCount" : 0,
    "coalition" : 372,
    "rpages" : 117383,
    "priority" : 10,
    "reason" : "highwater",
    "physicalPages" : {
      "internal" : [
        86883,
        28895
      ]
    },
    "freeze_skip_reason:" : "none",
    "pid" : 18901,
    "cpuTime" : 25.356921,
    "name" : "com.apple.WebKit.WebContent",
    "lifetimeMax" : 120432
  }
```

**Comment by ethanfann** [comment]
Spent some time looking into this and I'm also leaning towards a runaway memory issue @Watcher7. I have the sim running locally with a debugger attached to my iOS device and memory management most certainly does not like what's going on resulting in the tab being killed.

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/6005240/202403001-65a81ecc-010f-479e-aec8-b10855cb4134.png">

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/6005240/202404707-4ac8bfb9-c080-49cd-9728-9b951497816d.png">

We're currently spawning three web workers, each of which issues their own fetch for the wasm binary and I imagine go through the same init steps such as fetching gear lists.

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/6005240/202409409-d988316b-3815-49d4-a74b-98c5c9a7db29.png">

A few console statements show a rough order of operations. One wasm binary is ready before the others and starts sending messages. Tab crashes before the second or third become ready.

<img width="135" alt="Screen Shot 2022-11-17 at 1 26 13 AM" src="https://user-images.githubusercontent.com/6005240/202408510-e14faf9f-185d-4b58-9c37-887812837eba.png">

**Good News** Limiting to 1 web worker allows the sim to load and run, which could possibly be a bandaid fix until the root cause is found.

https://user-images.githubusercontent.com/6005240/202413001-10df98b2-f8b1-4637-bfd7-d91f7e36fd54.MP4

**Comment by Watcher7** [comment]
@ethanfann ah, thank you for taking the time to look into it as well. I was about to get around to attaching Safari to my own Phone, but a series of XCode and iOS updates caused Safari in both the simulated and physical devices to leapfrog both my laptops version wise. The version incompatibility seems to make the attachment impossible until the laptops are done updating, haha.

Any idea if the memory usage remains roughly stable while running the app with one worker, or just slow the climb while using?

**Comment by Watcher7** [comment]
I implemented the band-aid fix that was suggested via #1747 
Long term fix is to reduce total memory usage if 3 workers is desired on iOS.
This at least makes the sim run on iOS in the mean time.

**Comment by jimmyt857** [comment]
This is now presumed to be fixed, especially after #1781 which reduces the .wasm file size.

We can reopen if it occurs again.

**Comment by ethanfann** [comment]
Amazing! Thanks for everyone's work here, was going to take another look over the holiday weekend but looks like it's all sorted and I can confirm it's loading iOS Safari.

**Comment by blakeanedved** [comment]
This issue still seems to happen for me, or at least I assume it’s the same issue. Everytime I open the sim on iOS it reloads after a few seconds repeatedly. I have an iPhone 13 Pro, and I’ve tried in multiple browsers (safari, firefox, brave) which all yield the same result, and I’ve verified with a friend of mine that has an android and it works on his phone.
