### ISSUE TITLE
Expertise rating to expertise value convertion is wrong

### ISSUE THREAD

**Issue by Hati-** [wowsims/wotlk#1625]
Messing with the protection paladin sim I noticed that the expertise values were all over the place and incorrect. Upon investigating this I found out that the expertise-rating to expertise-value ratio is wrong:

https://github.com/wowsims/wotlk/blob/163bf38c9808360af9121c3b6f1cb60a6c55060f/sim/core/constants.go#L13

It seems to be using the hit-rating to hit-% ratio of 32.78. It should be the expertise-rating to expertise-value ratio of 8.19496 according to these tests:

![WowClassic_2022-11-07_07-51-50](https://user-images.githubusercontent.com/10211721/200243774-af43c3af-d96e-4970-a3b0-c29e0e1ee64e.png)

The tests were done on a level 80 Paladin on game version 3.4.0.46368. The second test has +6 expertise-value bonus from the Combat Expertise talent and a +3 expertise-value bonus from the human's Sword Specialization passive.
Also notice how the expertise-value from gear gets rounded down.

**Comment by psiven** [comment]
The displayed values of rating can be a little misleading because all other bonuses are included. If you hover over the expertise stat display it will show how much is from rating on gear, and how much is actually from talents converted to "rating" from Combat Expertise, Human racial, and/or Glyph of Seal of Vengeance.

Several of these values are *very* misleading at the moment, in particular avoidance totals are only sensible on the Detailed Summary page. But for this one I am pretty sure 32.79 / 4 is close enough.

**Comment by Hati-** [comment]
You are correct, I did not take Glyph of Seal of Vengeance into consideration when comparing to the value in-game. However, there seems to be a rounding error on the tooltip. It shows that the sword specialization causes the base expertise-value to go up by 2 when it should go up by 3, and that the Glyph of Seal of Vengeance causes the talent expertise-value to go up by 9 when it should go up by 10. The the total sum value is correct though.

**Comment by jimmyt857** [comment]
Closing, seems like this is WAI
