### ISSUE TITLE
Gems not filted by JC-profession

### ISSUE THREAD

**Issue by mmolignano** [wowsims/wotlk#1819]
JC gems are still showing under the selection menu even when JC is not a selected profession.

![image](https://user-images.githubusercontent.com/1290816/202901628-59dc7ecb-f3fd-41e1-87a4-84b533c49114.png)
![image](https://user-images.githubusercontent.com/1290816/202901643-23801c8a-ba40-4db7-b4cd-903abbf7f62f.png)

**Comment by jimmyt857** [comment]
This is actually intentional; we don't filter profession-locked items by default because many users poke around on the Gear tab first before getting into settings, and it would take awhile before they realize why the gems aren't shown. Instead, we have a warning in the top-right when profession-locked items are equipped without selecting the profession. Also, in the future we may add an explicit opt-in filter for this. Thanks for the report!
