### ISSUE TITLE
Shadow Priest sim

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#21]

**Comment by dbyena** [comment]
This may apply for most classes, but spell coeffients/talent resources can be found https://wotlk.evowow.com/

**Comment by CyberQuackGames** [comment]
Adding a few items to work through here with notes from beta testing. We may break these down into more PRs when the time comes or combine several pending how integration works out.

Priest Baseline:
- [ ] Base stats for 80
- [ ] Talents Proto Update (Going to go with full talent tree in case any healers / other use cases come up)
- [ ] Removal of priest specific racials (e.g. Shadowguard)
- [ ] (Shadow) Presets for Sim (Will require non-priest updates for consumes, party buffs, etc)
- [ ] (Smite) Presets for Sim (Should we remove in relation to #11 ?)

Abilities To Migrate (Notes / Updates):
- [ ] General Updates (Spell ids updated to new max rank, mana is based on base mana cost for all ranks)
- [ ] Mind Blast (Base mana, talent integration)
- [ ] Shadow Word: Death (Base mana, talent integration)
- [ ] Vampiric Touch (Base mana, base tick damage update, talent integration)
- [ ] Shadow Word: Pain (Base mana, talent integration, need testing on snap shot numbers for MF refresh)
- [ ] Devouring Plague (Baseline now for all priests. Improved Devouring Plague (talent) is 150% crit damage from testing)
- [ ] Shadowfiend (No mana now, need to integrate the new Shadowcrawl ability as well as get testing numbers)
- [ ] Mind Flay (Base mana, base tick damage update, talent integration, no longer considered a "dot" as a channeled spell)
- [ ] Dispersion (New. May need to consider breaking out of dispersion early in a later implementation)
- [ ] Mind Sear (New. Probably will be integrated at a later time if we can get multi target integration)

Talents to Update / Integrate (Sim damage usage only):
- [ ] Improved Spirit Tap
- [ ] Improved Shadow Word Pain (Moves from increased time to damage done)
- [ ] Veiled Shadows (Was Improved Fade, reduces Shadowfiend CD)
- [ ] Mind Melt (New. Crit chance on most spells)
- [ ] Shadowform (Allows all dots to crit and DP and VT to benefit from haste)
- [ ] Misery (Now grants 3% hit to raid instead of 5% spell damage debuff. Also buffs MB, MF, and sear SP gain)
- [ ] Vampiric Touch (Reworks mana gain to give replenishment buff on MB cast)
- [ ] Twisted Faith (New. Adds 20% of current spirit to spell power. Adds 10% more MB / MF damage if SWP is applied to target)
- [ ] Dispersion (See abilities above)

Rotations:
- [ ] TBD - Pending beta testing. Will need to consider several factors here including if/when MB and/or SWD are dropped from rotation based on gear as well as cast priorities from snap shot testing.

Potential Cross Over Work:
- [ ] Dot snap shot logic (Crit and SP % buffs)
- [ ] Misery as a preset / setting on other classes

**Comment by CyberQuackGames** [comment]
Leaving a note to checkout the [wotlk-beta-findings channel](https://discord.gg/a2PeNgKu) in priest discord.

**Comment by CyberQuackGames** [comment]
Notes on spirit from talents with no gear:

Base spirit: 155
Twisted Faith (20% of spirit): 31 SP
Glyph of Shadow (30% of spirit): 77 SP (Talent + Glyph are additive)
Improved Spirit Tap (10% more spirit): 85 SP (170 spirit)

**Comment by jimmyt857** [comment]
This sim is in alpha, remaining issues can be tracked in separate threads.
