### ISSUE TITLE
APL-like rotation input

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#2173]
Design a fully-customizable way (similar to APL in simc) which allows complete control over the character's rotation. Ideally, this system will be able to replace most or all existing rotations.

Here's a good reference for APL: https://github.com/simulationcraft/simc/wiki/ActionLists

In WoWSims, we probably will use a proto schema for this rather than raw strings. The `CharacterStats` API call could return all available spells / auras for each unit, allowing the UI to give the user dropdown lists for all the options rather than forcing them to memorize spell IDs.

**Comment by jimmyt857** [comment]
An important prerequisite for this will be to refactor the code for every spec to remove all assumptions of `CurrentTarget`.

**Comment by CharWS** [comment]
https://github.com/simulationcraft/simc/wiki/ActionLists That'd be an example of syntax and the types of things that would want to be able to control in an action list (auto attack, snapshots, spells, pet controls, external buffs, consumables, sequences, waits, resources, conditional expressions, time, cooldown alignment/sync, target health, channeling, off gcd abilities)
https://github.com/simulationcraft/simc/pull/7158 And here would be an example of what that could look like in practice, if you follow one of the links in that thread and open up the Raw Input can see how the APL has been laid out

**Comment by lime-green** [comment]
@jimmyt857 this APL feature is something I'm really excited about. It's going to be a huge undertaking so I think it has to be approached with incremental additions to the sim until we can replace rotations with an APL rotation. At a high level:

1. Add ability to optionally use an APL rotation engine (server flag)
2. Add default APL file to 1 or more specs starting with working syntax for extremely basic needs (auto attack, cast)
3. Keep adding to APL file and implementing APL engine logic to fulfill rotation needs until we can more or less match current rotation DPS
4. Add experimental flag in UI to enable APL rotation free-form text field 
5. Ask all spec developers to implement current rotation as APL file, fulfill APL engine logic as needed
6. Make APL rotation the default engine 
7. Remove old rotation engine 

I think it makes sense to follow the same APL syntax as simc unless there's a good reason not to, it's tried and true and will serve as a good yardstick. 

What do you think about this? I think #4 is quite important since it will empower users to create their own APLs and I think we'll be surprised at how eager people will be in min-maxing rotations. I believe once users get access to a basic APL for their spec a lot of the work can be done by them (having APL competitions in class discords?).

**Comment by jimmyt857** [comment]
@lime-green the steps you list are all great, I'd just like to note 2 points:

 1. Our version of APL won't be free-form text. In my opinion this is the biggest problem with APL; ordinary users are unable to use it until they learn an entire syntactic language, which means most never will. The huge range of options means it will never be simple, but by representing it internally as a hierarchical schema and giving the user an actual UI for editing (look at the Custom Rotation in hunter or enhance sim for the basic idea of what this looks like) at least we won't need to write an entire wiki site just to explain how it works. Representing as a schema also avoids having to write string-parsing logic in the sim. If we ever need to, converting from schema --> APL syntax will be a lot less work than the other way around.
 2. APL is much less expressive than a real programming language, and therefore there will be certain pieces of logic that can't be written with it. I'm expecting these to not be huge issues, but they will be there. Also it's likely that the APL implementation will be slower than the non-APL versions, as a result of being generic. Because of these 2 points it's possible we will end up keeping the old rotations permanently, to preserve a simplified rotation UI and better performance for some users.

**Comment by lime-green** [comment]
@jimmyt857 those are good points. I do think there’s value in a free form field though since it will be easier to share and quicker to iterate from a dev perspective. What do you think about starting with a field that accepts JSON which is sent via protobuf to ensure a consistent schema? Then we can migrate to an interoperable GUI that exports and imports from the JSON schema as well

**Comment by jimmyt857** [comment]
That's true, with so much variability in the rotations people will need an easy way to quickly share just their rotation settings.

The most natural way to include this in the existing UI would be to add a `Rotation` option in both the Import and Export drop-downs, which could either use base64-encoded binary or JSON formats. Open to other suggestions, but the exact UI for the import/export we'll probably revisit again anyway once we actually have something in front of us to talk about (which, again, won't be for quite awhile).
