### ISSUE TITLE
Protection Paladin Sims do not account for Base Parry or Deflection

### ISSUE THREAD

**Issue by Paulkik** [wowsims/wotlk#2242]
**Describe the bug**
Under Protection Paladin simulation, the 5% baseline parry is not accounted for under Stats. In addition, the 5% parry chance from the Ret talent, Deflection, are not in account under Stats. 

**To Reproduce**
1. [Go to '...'](https://wowsims.github.io/wotlk/protection_paladin/#)
2. Click on Simulator
3. Scroll down to Stats
4. Observe how Parry only takes into account gear bonuses, not talents or base parry

**Expected behavior**
Base parry is 5%, talents is 5%. In theory, a paladin with the Deflection talent should never fall under 10% parry.

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/56137495/210003426-01128885-caa7-49f1-893c-3d2bccdd4c0b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by psiven** [comment]
This is a display issue currently, proper avoidance levels can be observed in the Results tab.

In a future update the stats will show correct totals.

**Comment by jimmyt857** [comment]
@psiven if you want to expose pseudostat-based talents in the UI we can do so now, here's an example of how to implement it: https://github.com/wowsims/wotlk/pull/2172

Whether we want to include the base parry amount too is questionable, since it depends on the target and isn't really part of the Character's stats.
