### ISSUE TITLE
Moonkin/swift ret raid buff doesnt show in char stats

### ISSUE THREAD

**Issue by jarveson** [wowsims/wotlk#2244]
Pulling from discord report:

Selecting either raid haste buff doesnt reflect in char stats

<img width="941" alt="2022-12-29_141156" src="https://user-images.githubusercontent.com/536093/210021920-d7027fc0-717e-4f64-b780-38780683c8d5.png">

https://github.com/wowsims/wotlk/blob/eed69bff0384fbfa9224219c5039e88f864e518b/sim/core/buffs.go#L65-L67

changing these to `multiplyStat` instead may still accomplish same thing and show it in ui stats

**Comment by jimmyt857** [comment]
@jarveson this issue is actually very similar to #2242 in that it can now be solved by exposing the pseudostat to the UI. https://github.com/wowsims/wotlk/pull/2172 is a reference for how to implement.

The PseudoStats and Spell/Melee haste are not interchangeable because the pseudostats apply multiplicatively and haste rating applies additively.

**Comment by jimmyt857** [comment]
@psiven made a recent PR which is an even more succinct example of how to implement this: https://github.com/wowsims/wotlk/pull/2281

**Comment by jimmyt857** [comment]
Going to close this actually; this affect shouldn't be included in haste rating, because it is calculated differently.
