### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by daft93230** [wowsims/wotlk#2550]
https://www.wowhead.com/wotlk/item=46192/conquerors-nightsong-trousers why your item is different , no hit on yours

**Comment by Teebown** [comment]
![Screenshot_20230201-085511](https://user-images.githubusercontent.com/108202746/216077474-4e09adfb-f96c-4e84-9414-dda36f15efdf.png)
![Screenshot_20230201-085232](https://user-images.githubusercontent.com/108202746/216077481-aa9685b7-73ed-45b9-9c06-68595ce25ae3.png)
![Screenshot_20230201-085223](https://user-images.githubusercontent.com/108202746/216077484-139524cb-f2e8-47ba-8ba2-a38497c6b7a5.png)
It looks like you might have been looking at the leggings and not the trousers, because I see the trousers correctly in the sim item drop-down?

**Comment by jimmyt857** [comment]
Going to close this as resolved, but if there is still a problem feel free to reopen.
