### ISSUE TITLE
[REQUEST] Raid Sim: Blood DPS icon change

### ISSUE THREAD

**Issue by NuptupTDOW** [wowsims/wotlk#2561]
**Is your feature request related to a problem? Please describe.**
The icon for Blood DPS in the raid sim uses the Rune Strike Icon, which is a predominantly Tank DK ability. It leads to a bit of confusion and I'd like to offer an alternative.

**Describe the solution you'd like**
I believe that the best Icon for Blood DPS in the sims would be Heart Strike. It is almost only used for Blood DPS or deep blood tank specs since most other blood tank specs opt out of it to get into frost deeper and the other DK DPS options have no way to get Heart Strike. It's pretty much THE spell that Blood cares about and I think it'd be a great change to make the spec distinction more clear. I have alternatives listed below, in the event you want to drastically change how specs are handled, but this solution of JUST changing Rune Strike to Heart Strike would be much simpler and serve the same purpose.

**Describe alternatives you've considered**
I've also considered maybe classifying the different DK specs in the raid sim using their most note-worthy ability icon since leave heart strike as dps but the blood presence icon as tank can lead to more confusion. Examples of each would be as follows:

Blood Tank: Death Strike or Will of the Necropolis, both are what blood tanks are known for and they're unique from other class icons as well.
Frost Tank: Frigid Dreadplate, pretty much the only one I can think of that would be distinct. Could maybe argue Frost Presence still since it's unquestionably the tank presence.
Unholy Tank: Bone Shield, also iconic for tank dk's, especially when added to blood in Cata. It's recognizable and makes sense.
ALL TANK SPECS: since the raid sim groups all of the dk tanks into one icon, you could just use Frost Pres here, then distinguish the dps by main ability as seen below.

Blood Dps: Heart Strike. Just Heart Strike. (See above)
Frost DPS: Obliterate. Just Obliterate. It's entirely too iconic not to use it.
2-Hand Unholy: Scourge Strike. It's what makes 2-hand vs Morb different for 2-hand.
Morb Unholy: Death and Decay. It's pretty much what Morb is based around, besides Gargoyle, but I feel Death and Decay is clearer.
Unholy is currently just 1 icon since the Morb vs 2-hander is all handled inside the Unholy spec sim itself, so alternatively you could use the Ghoul icon for Unholy since that's their unique mechanic.

**Comment by kayla-glick** [comment]
Hey @NuptupTDOW 👋 the icon we use for DPS Blood is the same one that we've been seeing in Warcraftlogs. IIRC (and someone please correct me if I'm wrong) DPS Blood is labeled as "Runeblade" and uses the Rune Strike icon. We don't actually have the ability to distinguish between other "Runeblade" builds at the moment because we haven't found a way to grab talents from WCL to make the distinction. Hopefully this helps explain why we made the decision to use that icon 😄 I definitely hope that WCL will distinguish Blood DPS at some point and if they do we'll definitely do the same.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/12898988/216222089-8b540c9f-015b-43c3-969b-d09c3b5c0ada.png">

**Comment by NuptupTDOW** [comment]
Huh, alrighty, that's I guess nice to know. So, it's effectively the "off-tank/Blood DPS" icon. Hmmmmmmmm. Well, here's hoping that can be addressed before blood dps starts to actually perform. It's already simming higher than warriors and ret pally's, so.., hopefully it'll be treated equal to them sooner than later.
