### ISSUE TITLE
Crystal Yield - Debuff

### ISSUE THREAD

**Issue by Apoc1994** [wowsims/wotlk#2666]
**Is your feature request related to a problem? Please describe.**
Yes this feature would add Crystal Yield, a popular parsing item, to the choice of available debuff section. 

**Describe the solution you'd like**
I'd like Crystal Yield to be added to the debuff section of the Sim.

**Describe alternatives you've considered**
There are no other alternatives unfortunately. 

**Additional context**
Here's the Wowhead link to the spell's name. https://www.wowhead.com/wotlk/spell=15235/crystal-yield

**Comment by where-fore** [comment]
To clarify the mechanics of this strange item:

As it reads on the tooltip, it reduces 200 armor of the target. This is applied to the base armor before debuffs like Sunder Armor which remove a percentage of armor - eg. with Sunder Armor active, a 1000 armor target will have 800 armor. With Crystal Yield and Sunder Armor active, a 1000 armor target will have 800*0.8=640 armor (before all the reducible armor shenanigans you'd regularly expect)

While the item reads a 2 minute duration, it is easy to produce and reapply, and likely should just be a on/off toggle like other debuffs.

As an alternative before this is added, you can manually add an amount of Armor Penetration Rating to your character. Due to Armor Penetration Rating's self scaling nature, this is difficult to produce a figure, and inaccurate if Armor Penetration Rating changes during combat, say from a Mjolnir Runestone proc. At 0 Armor Penetration Rating, 27.5 extra rating mimics the debuff. At 1000 Armor Penetration Rating, 20.5 extra rating mimics the debuff.

I have lost the primary tests that prove these, but they were done on Maexxna through Beast Lore in Phase 1, and could be recreated at any time.
