### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Deroonk** [wowsims/wotlk#2692]
I would like to see an option in the combat rogue rotation settings to only use a rupture at 5 combo points

**Comment by vigo2** [comment]
The combat rotation has been updated to prefer high CP ruptures, as long as you don't provably lose DPS doing so. The end result is something like

![Screenshot 2023-03-29 at 09 58 35](https://user-images.githubusercontent.com/9415187/228473657-a6372026-baee-47c5-b7d8-adab7e07a03d.png)

so _most_ rupture casts are now 5 CP.

**Comment by vigo2** [comment]
Conversely, using only 5 CP Ruptures is provably a DPS loss (whenever the ~9% higher DPS is delayed by more than ~9% of a 4 CP Rupture's runtime, or roughly 1.5 seconds - way too short for adding another CP, in general).

Since it won't be a DPS increase, and only adds interface complexity, I'm against implementing this as an option.
