### ISSUE TITLE
Adding Items with the original wotlk ilvls/stats in addition to the existing wotlk classic ilvls/stats

### ISSUE THREAD

**Issue by KryptixGG** [wowsims/wotlk#2741]
**Is your feature request related to a problem? Please describe.**
I would like to Sim item sets with the items of original Wotlk. Items like "Watchful Eye of Fate" used to be 226 ilvl instead of 239 and therefore had different stats (as seen in https://wotlkdb.com/?item=45447 compared to the wotlk classic item: https://www.wowhead.com/wotlk/item=45447/watchful-eye-of-fate)

**Describe the solution you'd like**
I would like the original items to be added to the itempool and for better usability maybe an option to activate/deactivate the original version of items.

**Describe alternatives you've considered**
Another option would be to add the possibility to add custom items yourself so that the - most likely fewer people - who are interested in simming itemsets of the original items can add these items for themself only.

**Additional context**
I think this feature would make the tool usable for private server players aswell in case this project cares about those too.

This is my first time using gitub, i hope i did this properly :)

**Comment by napnapnapnap** [comment]
Agree, this would make it useful and reliable for lots of people who still rely on old versions of Rawr

**Comment by lologarithm** [comment]
This would be fairly complicated because the items would have the same ids but different stats/bonuses. To start we use wowhead for our item data and it uses all the new ilvls, so we would need a source for the data. We currently load all the items as a json database, so we could theoretically provide some way to load a different item database. However, all the active effects are coded into the sim itself and so would require custom implementations for every active item.

This sounds like it probably would be best to just fork the whole project and you could replace all items and effects. 

Additionally private servers often have different combat formulas that result in different damages done so you would probably need to rewrite most the combat code to support whichever private server you are running on. 

All in all this would be a huge project and wayyyy outside the scope of what we are doing for classic wotlk.
