### ISSUE TITLE
Crash Report 1283064485

### ISSUE THREAD

**Issue by notwarin** [wowsims/wotlk#2990]
Link:
https://wowsims.github.io/wotlk/warrior/#eJzjkuJgMmDKYCxgbGBkXMHIeIGR8QUj4w9GpgtMTE78CkwOQJkOsMwORkYhBqljbE2MbAE5iZWpRRzsApxS1xm5+AWOv2CSeCmrxLbtMNO5s0xcnAKTHzMpMT/dwQSUu/qcSeIBUA7IAwmwC7zZzCQxVQYocwio6wdQZt5JJiDi4hKYvYlJolVOiZGBi1fgCFByiowSC1CGAah250MmJc7DO5j27GA6DDb2GFD+PbKx/XuZJKbJAO3+9BJqN6fAiidQJovAzU0g8vV5kN4zj5kkziL08guseYYiwCIw7wGTEgcwYNgCmCNYFjF9ZeI6wMQwCigCQgak6qhi4WCUYCry5XIWYJzAyKjAqMHkCJGxc/AE0w2ODoEQkUiHSAjD0gGUmCtAyRmYbhcyQkRNHKTYBIAmSDB1MUYZW5j6mle4leWHBbunewcFeDklGgaaZgQbulukJJUV5Jpl6xobmBqYGBsYGJgaGRgbAiljQyOgkKGxqaGuAW7wiFGCY8VlJoFZl4GJ8TKTQutlJo09/5kMWi4zvWBk+cDIPouR4RYjwywmBqVuZk6IF9IcBCFuFHGQnDUTBE7aW0JELtgrpoHBNXuj20wKwRKsWjROhx8aHahhTMPJI1QxhxYAErZ73ztA09IP+wTGIHAOP/xVI6b/EKuDfOvrwB1yf+2pa+8He4+HVSLr3F/afwNZ85XBAWxN6297EE8jhtEBEtcsDrhMACoG6phHZXdRDwgZaIK9IumwpMCW6/piHgdCOqIUIPQHnH4CAMjMx74=

RNG Seed: 770211836

runtime error: index out of range [8] with length 4
Stack Trace:
goroutine 10 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0x18ed20, 0x1868978})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/warrior.(*Warrior).applySuddenDeath(0x1bf6000)
	/home/runner/work/wotlk/wotlk/sim/warrior/talents.go:583 +0x62
github.com/wowsims/wotlk/sim/warrior.(*Warrior).ApplyTalents(0x1bf6000)
	/home/runner/work/wotlk/wotlk/sim/warrior/talents.go:58 +0x7f
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x1bf6000, {0x3605b8, 0x1b83540}, 0x1b15040,

**Comment by zku** [comment]
Hey @notwarin - how did you come about these settings? Did you copy paste the export link first? Did you generate the link on your machine or did someone send it to you? The talent string looks completely off, and I suspect this is due to malware.

Your talent string looks like this: `385M7xFvoVSGgKRPJBa1Q5hS1G8dbvpm6k-305043000520310053120501351-000000000000000000000000000`

The 3 parts of this message represent the 3 talent trees, and the individual numbers represent how many talent points you spend per talent. The second and third talent trees look normal: we see numbers ranging from 0 to 3 or 4 or 5 - these numbers make sense for talents. We also see all 0s for the protection specialization, which seems expected for a DPS fury warrior sim.

However, your first talent tree, arms, looks completely off: `385M7xFvoVSGgKRPJBa1Q5hS1G8dbvpm6k`. The numbers make no sense (8 talent points?), and we also have various characters from the alphabet in here like `M` or `x` or `F` - these make no sense.

As to why I suspect malware: `385M7xFvoVSGgKRPJBa1Q5hS1G8dbvpm6k` appears to be a valid Bitcoin address: https://www.blockchain.com/explorer/addresses/btc/385M7xFvoVSGgKRPJBa1Q5hS1G8dbvpm6k

Various families of malware replace bitcoin-looking addresses in your clipboard (when you copy and paste something) with the address of the attacker, e.g. https://securelist.com/copy-paste-heist-clipboard-injector-targeting-cryptowallets/109186/

Do you have any other information / context on how this link was generated or how you created your talent tree in the sim that caused this crash? Anything else that could explain this?
