### ISSUE TITLE
Haste display of stats does not appear to update with changes to buffs

### ISSUE THREAD

**Issue by Zedseayou** [wowsims/wotlk#3121]
**Describe the bug**
In the warlock sim, changing other buff availability like spell crit/spell damage is immediately reflected in the effect stats shown on the left side. However, this doesn't seem to be true for spell haste (from ret pally aura, moonkin aura and wrath of air totem). Adding or removing those buffs doesn't change the displayed haste at all. Note that I think this is purely visual - the simmed dps numbers do change. I didn't check every sim but it appears to also be the case for melee classes and melee haste as well.

**To Reproduce**
1. Go to Warlock sim
2. Click on P2 affliction preset
3. Scroll down to spell haste, which shows 19.27% from base + gear and 0 for all other categories
4. Toggle the spell haste buffs in the settings on and off ("Haste%" from Swift Retribution or Improved Moonkin Form and "Spell Haste" from Wrath of Air totem)
5. See that the number does not change in any combination

**Expected behavior**
I expected the displayed haste values to change as they do when toggling other buffs.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Ventura 13.4
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 113.0.5672.126

**Comment by where-fore** [comment]
This is correct behaviour, those talents or effects you are describing do not give any haste rating. How haste effects stack:

(Sum of all your haste rating from all sources) / (Haste Rating Coefficient) = Haste Percent from Rating
(Haste Percent From Rating) * (Haste Buff 1) * (Haste Buff 2) * (Haste Buff 3).. etc = Total Haste Percent Multiplier

Since the haste buff from the buffs you mention is multiplicative with rating, the conversion of that buff into equivalent rating would be dependent on your current haste rating. I think it would be confusing for the buff to give you different amounts of fake rating depending on your current rating.

A link to a discussion on the development discord for further reading: https://discord.com/channels/891730968493305867/891807022973087825/1095417637204398252
