### ISSUE TITLE
Improve the performance of Stats Weights computation

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#3164]
**Is your feature request related to a problem? Please describe.**
When the number of iterations is very high (450,000+), Stats Weights computation stalls. I suspect this is caused by too many resources being used and the browser decides to stop the thread to avoid crashing.

**Describe the solution you'd like**
I have 2 ideas how to improve the situation.
1. The issue happens for my Arms Warrior, and for that character, the simulator computes 11 weights. The last one is Off Hand DPS, which doesn't make sense because Arms Warriors use two-hand weapons. So we could already save 2 simulations entirely by removing the Off Hand DPS line from the report.
2. I monitored the memory consumption and found that it was steadily increasing throughout the stats weights computations, going over 3 GB. While I do understand that you need to perform a complete simulation and keep all the results in order to perform an average, the computation of each stat weight should be independent from the computation of other stat weights. So the maximum memory consumption should be reached after the first stat weight has been computed, which isn't the case. I am not familiar with javascript but I would hope that it is possible to explicitly free the memory which you know you will no longer need? Or, alternatively, maybe you could reuse the same data structures for each stat, to force the javascript engine to reuse the same memory?

**Additional context**
I started using very large iteration numbers after I was told in issue #3154 that this is required to get accurate weight values for Warriors due to how rage generation works.

**Comment by Tharre** [comment]
> While I do understand that you need to perform a complete simulation and keep all the results in order to perform an average, the computation of each stat weight should be independent from the computation of other stat weights. So the maximum memory consumption should be reached after the first stat weight has been computed, which isn't the case.

The reason why this doesn't end up being the case is because the stat weights are computed in parallel.

> I am not familiar with javascript but I would hope that it is possible to explicitly free the memory which you know you will no longer need?

We actually use go compiled to WASM and not javascript, though in both cases everything is garbage collected, meaning manually freeing memory is not possible but shouldn't be necessary either. Rather the likely reason why memory usage goes up so much is because we keep too much data from every iteration, which isn't used in the actual calculation of the weights but the garbage collector can't free either because it may only operate on entire structs.

A workaround would be using the downloadable version of the sim, which allows much more memory to be used while also being much faster in general.

**Comment by jdelvare** [comment]
I switched to the downloadable version in order to compute the stats weights on my arms warrior, thanks for the hint.

My point about computing the Off Hand DPS on a character holding a two-hand weapon still stands ;-)

**Comment by jimmyt857** [comment]
There's no practical solution here which would make a meaningful difference, and we have a recommended workaround (use the downloadable version). So closing this.
