### ISSUE TITLE
Results->Timeline: Horizontal scrollbar positioning

### ISSUE THREAD

**Issue by KryptixGG** [wowsims/wotlk#3224]
**Is your feature request related to a problem? Please describe.**
The horizontal scrollbar is at the bottom making it very iffy to use when checking the rotation as the most important rows are at the top.

**Describe the solution you'd like**
Put the horizontal scrollbar at the bottom of the currently visible portion of the table as kind of a HUD, make it visually part of the website below the table instead of part of the table or move it when it is being scrolled up/down so that it is allways visible/usable.

**Describe alternatives you've considered**
Just put the horizontal scrollbar at the top, if my wished solution is too annoying/complicated to do.

**Additional context**
-

**Comment by rosenrusinov** [comment]
A solution to this is holding Shift while scrolling (this will make your mouse scroll wheel do trigger the horizontal scroll instead of the vertical one)

**Comment by KryptixGG** [comment]
Oh, i didnt know that was possible, sorry. My request might be irrelevant then. Unless you wanna implement it for other users who might not know this either. I cant assess if that would be worth the work.

**Comment by rosenrusinov** [comment]
Your request is still relevant so I would leave it open if someone wants to tackle it 👍

**Comment by kayla-glick** [comment]
I looked into this a bit and because of the way scrolling content works on webpages we can't preserve the "stuck" labels on the left hand side with a fixed size container with scrolling overflow. You can only get the horizontal scrollbar on the outer container which makes you lose the labels. I could do some funky stuff to force it but I have to put a background on the labels to obscure the timeline as it passes over like in the SS below.

![image](https://github.com/wowsims/wotlk/assets/12898988/70b6ac88-a85d-493a-b6e7-23159dbd573a)

We could also add a note that says something like "Hold shift to scroll timeline horizontally"

**Comment by kayla-glick** [comment]
Hey @KryptixGG I ended up adding two things:
1. You can now click and drag the timeline to scroll it, and
2. I added a note about being able to click and drag, as well as holding Shift+scrolling

Hopefully it'll be a bit easier to navigate the timeline going forward!
