### ISSUE TITLE
Stormjewel gems are no longer unique

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#3247]
**Describe the bug**
The simulator does not allow several Stormjewel gems on a given item.

**To Reproduce**
1. Equip an item with 2 gem sockets or more.
2. Put a Stormjewel in the first socket.
3. Put a Stormjewel in the second socket.
4. The first Stormjewel gets removed.

**Expected behavior**
Since P3 Stormjewel gems are no longer unique, so the simulator should allow multiple of these.

**Comment by catszeid** [comment]
Stormjewels are working as intended and are Unique-Equipped so only one can be equipped per variant. However, there are other Epic rarity gems available via Jewelcrafting that provide the same amount of stats and are not restricted in how many can be equipped. 

If you wish to use multiple of Epic rarity gems, you should be using the Jewelcrafting versions rather than Stormjewels.

**Comment by catszeid** [comment]
I appreciate you pointing out that Wowhead is lagging behind, but there is not much we can do to force such an update. The issue will be fixed when Wowhead has updated the data, but until then it will not be reflected. For now you should use the Jewelcrafting equivalent gems.
