### ISSUE TITLE
Change the APL of Survival

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#332]
**Is your feature request related to a problem? Please describe.**
I checked the timeline of survival to see what he is doing and realised that the prio is kinda weird, so i checked your code and found out that the Prio is wrong for Survival.

**Describe the solution you'd like**
The prio should be Kill Shot>Explosive Shot>Explosive Trap/Black arrow > Aimed shot > Serpent Sting > Steady Shot.

**Additional context**
Also i am still not sure how your steady is 1.58 casttime, if the spell has only 1.5 casttime ? or is there something wrong? did i miss something? 
Here u can see it yourself: https://gyazo.com/c3feab2b94a188026664f20e864fcc91

**Comment by jimmyt857** [comment]
The rotation is still very simplistic. I'm waiting until beta settles a bit more and the meta rotations are established, and then I'll rework all the rotations.

The base steady shot cast time is currently set to 2 seconds because I've had multiple beta testers tell me it is 2s. I'll change that if I get confirmation otherwise.

Going to close this because everything is WAI for now.
