### ISSUE TITLE
Killshot not working properly

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#354]
**Describe the bug**
Basically its used only once (sometimes even never) in the fight no matter the fight length. I checked if something changes when i put the KS Glyphe in to reduce the CD but it has basically no effect. I dont really think that the glyphe is not working but rather something is wrong with the prio for KS. Maybe an If-statement is wrong? Or is the execute phase bugged or something? I also dont see KS in the Timeline anymore. 

**To Reproduce**
1. Sim for 180 sec
2. Check KS
3. Change fight length
4. Check KS
5. Change Glyphe
6. Check KS
7. Also check the Timeline when KS been used.

**Sim Links and Screenshots**
No KS in Timeline as u can see. I think its this last Square on the right out of bound: https://gyazo.com/7221d984e25ccf8b2f63924cec98c746
As u can see only 1 KS on 240 sec Fight length: https://gyazo.com/9007d20cf77e35762aa608c1aee818f6

**Desktop (please complete the following information):**
 Windows 11
Chrome

**Additional context**
Also it says that i spent 0,1 sec OOM even tho i had still 70% mana. https://gyazo.com/93cefb1892cb50dcb3a1df1531f2dd0c
I checked the buff uptime for Aspect of the Viper and it said it was 0,09% of the fight up. Thus i checked the timeline but didnt find it.
Thats the case when i put fight length on 240 sec.

**Comment by jimmyt857** [comment]
This is due to a weird interaction we currently have with our execute phase settings. Go to Encounter --> Advanced --> and set `Execute Duration 25%` to 25 (it is probably incorrectly set to 0 right now). Or you could instead go to top right cog wheel -> Restore Defaults.

We'll have to figure something out to make this more intuitive. For now I'll at least make it so that values of 0 default to non-zero numbers.
