### ISSUE TITLE
Strict Sequence with Blood Tap doesn't work as expected

### ISSUE THREAD

**Issue by blu3bird** [wowsims/wotlk#3548]
I have this Strict Sequence:
![Screenshot from 2023-08-22 22-55-17](https://github.com/wowsims/wotlk/assets/1130532/c0877027-c7de-4507-be91-42e84cf34d78)

I expect it to be executed if these conditions are met:
- Blood Tap is not on cooldown
- Ghoul Frenzy is not on cooldown

But instead it only executes if these conditions are met:
- Blood Tap is not on cooldown
- Ghoul Frenzy is not on cooldown
- At least 1 unholy rune is available

Because Blood Tap will grant you one death rune immediately there is no need to wait for an unholy rune.

Steps to reproduce:
- open the [death knight sim](https://wowsims.github.io/wotlk/deathknight/)
- select whatever gear and settings you want (encounter duration must be at least 11 seconds)
- select "Unholy DW SS" talents
- select "Unholy DW SS APL" rotation
  - it has the Strict Sequence mentioned above in it
  - disable the Ghoul Frenzy Prepull Action
  - disable Autocast Other Cooldowns
  - disable Summon Gargoyle Priority
- simulate
- go to Results -> Timeline
  - Blood Tap/Ghoul Frenzy is execute at second 11 when it should be execute at second 4

**Comment by rosenrusinov** [comment]
@jimmyt857 this ones an interesting one. I wonder if we should even do something about it. In practice strict sequences do have the requirements that all actions in the sequence can be executed before the sequence is started. Maybe we can have another type of strict sequence that would only check for the first action and then fail out if it goes to an action it cant cast?=

**Comment by jimmyt857** [comment]
This is the same problem I was running into with warrior stance dancing, it's not possible to write a strict sequence like, "Battle Stance --> Thunderclap --> Berserker Stance" even though that would be the simplest and most intuitive way to accomplish the goal.

I suspect we want to solve this somehow, but I don't know the answer either. The first thing I'd like to know is, how would simc's APL accomplish this. If there is an established way of handling this then we can mimic them, otherwise we'll have to consider something like your suggestion.
