### ISSUE TITLE
"Suggest Gems" functionality tends to forget about expertise cap.

### ISSUE THREAD

**Issue by BorniPL** [wowsims/wotlk#3604]
**Describe the bug**
"Suggest Gems" functionality doesn't always go for expertise cap.

**To Reproduce**
1. Load Horde P3 BIS set from
https://www.wowhead.com/wotlk/guide/classes/druid/feral/dps-bis-gear-pve-phase-3#horde
[wowsims.zip](https://github.com/wowsims/wotlk/files/12507776/wowsims.zip)
2. Use "Suggest Gems" button
3. Expertise drops down to 168 (5.12%)

**Expected behavior**
Expertise doesn't go above 214 (6.5%), but doesn't go below 200 too.

**Sim Links and Screenshots**
![image](https://github.com/wowsims/wotlk/assets/1348887/91746868-8c19-442d-a8cc-5b3594226240)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2009
 - Browser: Firefox
 - Version: 117.0 (64-bit)

**Comment by jarveson** [comment]
You can semi fix it by swapping to arp food instead which frees up two slots for expertise instead which gets you to 208/6.3% or if you set jc profession which frees up a slot for another epertise gem, which is prolly the closest you can get. without the food or jc in this case, the problem is either way ur either giving up either arp soft cap or expertise cap, or changing a yellow w/ socket bonus, which ends up being a wash and/or dps loss
