### ISSUE TITLE
Buffs

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#4]
Buff stacking is different (only 1 buff / category) and the buffs themselves are different of course.

**Comment by jimmyt857** [comment]
List of buffs: http://forum.warmane.com/showthread.php?t=367833

**Comment by CharWS** [comment]
One adjustment for that list would be inspiration and ancestral healing are changed from %armor to %damage reduction in patch 3.2.0, which would put them in the damage reduction category with sanctuary, vigilance, and renewed hope.

"[Inspiration]: The buff from this ability now reduces the physical damage taken by the target by 3/7/10% instead of increasing the target's armor."

"[Ancestral Healing]: The buff from this ability now reduces the physical damage taken by the target by 3/7/10% instead of increasing the target's armor."

https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0

**Comment by lologarithm** [comment]
Only buff left at this point that I am aware of is Demonic Pact
