### ISSUE TITLE
Missing items: from summer event [The Frost Lord's Battle Shroud, The Frost Lord's War Cloak]

### ISSUE THREAD

**Issue by Cure-whitemane** [wowsims/wotlk#4252]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:

- https://www.wowhead.com/cata/item=54803/the-frost-lords-battle-shroud
- https://www.wowhead.com/cata/item=54802/the-frost-lords-war-cloak

**Comment by kayla-glick** [comment]
Hey @Cure-whitemane 👋 I'm not sure if you meant to post this in our Wrath repo or if it was meant for the Cata version, but I see the old Wrath versions in the Wrath sim:
![Image](https://github.com/user-attachments/assets/80a11a63-3ff3-40c3-a215-2756f3b69122)

And the cata versions in the cata sim:

![Image](https://github.com/user-attachments/assets/9d8ae94d-3c88-40e8-812e-3475e66a023f)

We don't include the 232 versions in the Cata sim because they're below a reasonable ilvl threshold (I believe we use 272 as a minimum with some exceptions

**Comment by Cure-whitemane** [comment]
@kayla-glick ah, right, thank you! It was about the filter: in the phase 1 there ar no such cloaks (which I believe it should be presented in p1, not only on p5)

![image](https://github.com/wowsims/wotlk/assets/173875910/97ae89a7-50e1-4aa2-a361-779e0a81ad97)
