### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by bayron3** [wowsims/wotlk#976]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
A ton of items from TBC were removed at some point today. To name a few:
https://www.wowhead.com/wotlk/item=34679/shattered-sun-pendant-of-might
https://www.wowhead.com/wotlk/item=28672/drape-of-the-dark-reavers
https://www.wowhead.com/wotlk/item=34616/breeching-comet
https://www.wowhead.com/wotlk/spell=36351/belt-of-deep-shadow
https://www.wowhead.com/wotlk/item=28034/hourglass-of-the-unraveller
https://www.wowhead.com/wotlk/item=29383/bloodlust-brooch
https://www.wowhead.com/wotlk/item=30724/barrel-blade-longrifle

Plus many, many more TBC items are gone

**Comment by jimmyt857** [comment]
This was intentional, as they cause large increases in website loading time and are quite irrelevant. We've kept everything from Hyjal and above which should be more than sufficient for wotlk purposes.

Specific items below the cutoff are allow-listed if they have interesting effects that make them relevant for lvl 80 content. If we've missed one of those then feel free to identify it.

**Comment by bayron3** [comment]
That's unfortunate as people try to gear during pre-patch and early wrath content. As of yesterday, this was the only working hunter sim for wotlk. Today, there is none.

**Comment by jimmyt857** [comment]
The sim assumes lvl 80 spells/coefficients/abilities so either way it's not accurate for that situation.
